server:
  port: 7003
eureka:
  instance:
    hostname: eureka3
  client:
    fetch-registry: false    #是否要从注册中心获取注册信息 , 解决eureka启动时报错
    register-with-eureka: false    #是否要注册到eureka, 解决eureka启动时报错
    service-url:
      defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka
    server:
      eviction-interval-timer-in-ms: 60000    #设置清理的间隔时间，ms (默认是60秒）
      enable-self-preservation: false       #设置为false表示关闭保护模式,在保护模式下，如因为网络或其它问题服务提供者掉线的话，eureka不会立即清空服务列表.
spring:
  security:
    user:
      name: admin
      password: a
